# Generated by Django 4.0.4 on 2023-06-10 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('codigo_banco', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('codigo_bodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_bodega', models.CharField(max_length=25, unique=True)),
                ('direccion_bo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('capacidad_ocupada', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('numero_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_boleta', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codigo_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutcliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre_cli', models.CharField(max_length=25)),
                ('apellido_cli', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
                ('razon_social', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('productos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Producto',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.estado_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo_proveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=25)),
                ('apellido_pro', models.CharField(max_length=25)),
                ('direcion_pro', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigo_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id_sabor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_sabor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo_sucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_sucursal', models.CharField(max_length=25)),
                ('nombre_sucursal', models.CharField(max_length=25)),
                ('direccion_sucursal', models.CharField(max_length=25)),
                ('capacidad', models.IntegerField(default=800)),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.comuna')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id_tamano', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_tamano', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tranferencia',
            fields=[
                ('codigo_transferencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('monto', models.IntegerField()),
                ('codigo_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut_trabajador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre_trabajador', models.CharField(max_length=25)),
                ('apellido_trabajador', models.CharField(max_length=25)),
                ('fecha_nac', models.CharField(max_length=25)),
                ('codigo_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.cargo')),
                ('codigo_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo_provincia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=25)),
                ('codigo_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.region')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sabor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tamano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.tamano'),
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('codigo_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=25)),
                ('codigo_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_items', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.PositiveBigIntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='VentasdeHelados.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='VentasdeHelados.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Guiadedespacho',
            fields=[
                ('codigo_guia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_guia', models.CharField(max_length=25)),
                ('condicion', models.CharField(choices=[('cancelado', 'cancelado'), ('en retraso', 'en retraso'), ('en preparacion', 'en preparacion'), ('en reparto', 'en reparto'), ('en camino', 'en camino'), ('entregado', 'entregado')], max_length=25)),
                ('tipo_retiro', models.CharField(choices=[('retiro en tienda', 'retiro en tienda'), ('envio a domicilio', 'envio a domicilio')], max_length=25)),
                ('direccion', models.CharField(max_length=200)),
                ('num_departamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.comuna')),
                ('codigo_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_factura', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('codigo_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal')),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('id_det_bo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.bodega')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('id_detalle_factura', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.producto')),
                ('numero_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id_det_bo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.producto')),
                ('numero_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.boleta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='codigo_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.provincia'),
        ),
        migrations.AddField(
            model_name='compra',
            name='codigo_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.carrito'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='codigo_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='rut_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.trabajador'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='codigo_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentasdeHelados.sucursal'),
        ),
    ]
